alias start_jp2='sudo sslocal -c /etc/shadowsocks/config_jp2.json -d start'
alias stop_jp2='sudo sslocal -c /etc/shadowsocks/config_jp2.json -d stop'
alias matlab='/usr/local/Polyspace/R2019b/bin/matlab > /dev/null 2>&1 &'
alias clion='~/space/third_party/clion-2019.2.5/bin/clion.sh > /dev/null 2>&1 &'
alias wcd='cd /home/ruiqun/space/Nutstore/Project/kubot-ros2'
